### PR TITLE
:tada: 

### PR DESCRIPTION
**Pull request by slimlime**
Sup

### CODE REVIEW

**Comment by slimlime** [comment]
lol

**Comment by slimlime** [comment]
Cool diagrams d00d @seant1 

What is this neuomorphism gross new GitHub design

https://github.blog/changelog/2020-06-23-design-updates-to-repositories-and-github-ui/

Where are the shadows
y so flat

**Comment by seant1** [comment]
hey my dude. eww what is this. what is happening. why is my square profile picture in a circle 😳

shadows don't work in dark mode haha

**Comment by seant1** [comment]
The rest of my team did all the work for this assignment on github web here. only changing one file at a time and no other git commands 😅😐😳😳

**Comment by slimlime** [comment]
lol
nice ones

hmm true black

dw looks funs :D

pro pull request per commit for exTRA code review documentation project manager man

🍡 🍙 :mango: 🥭
image
Hmm org and org profile still square!
Think outside the square non-conform

**Comment by slimlime** [comment]
:O fork delete button but then pull request am become the sad? :steamsad:

**Pull request closed without merging**
